// <auto-generated />
using System;
using Fleet.TransportationManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fleet.TransportationManagement.Migrations
{
    [DbContext(typeof(TmContext))]
    [Migration("20190927151238_InitDatabase")]
    partial class InitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fleet.TransportationManagement.Models.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label");

                    b.Property<decimal>("Latitude")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 38, scale: 17)))
                        .HasColumnType("decimal(10,7)");

                    b.Property<int?>("Load");

                    b.Property<decimal>("Longitude")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 38, scale: 17)))
                        .HasColumnType("decimal(10,7)");

                    b.Property<int?>("Refuel");

                    b.Property<int?>("TripId");

                    b.Property<int?>("TripId1");

                    b.Property<int>("Type");

                    b.Property<int?>("Unload");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("TripId1");

                    b.ToTable("Point");
                });

            modelBuilder.Entity("Fleet.TransportationManagement.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ResidualFuel");

                    b.Property<int>("TruckId");

                    b.HasKey("Id");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Fleet.TransportationManagement.Models.Point", b =>
                {
                    b.HasOne("Fleet.TransportationManagement.Models.Trip")
                        .WithMany("InputPoints")
                        .HasForeignKey("TripId");

                    b.HasOne("Fleet.TransportationManagement.Models.Trip")
                        .WithMany("OptimizedPoints")
                        .HasForeignKey("TripId1");
                });
#pragma warning restore 612, 618
        }
    }
}
