// <auto-generated />
using System;
using Fleet.TransportationManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fleet.TransportationManagement.Migrations
{
    [DbContext(typeof(TmContext))]
    [Migration("20200410115004_AddNonOptPoints")]
    partial class AddNonOptPoints
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Fleet.TransportationManagement.Models.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<double?>("Cost");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name");

                    b.Property<double?>("Refuel");

                    b.Property<double?>("Remainder");

                    b.Property<string>("TripId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("Point");
                });

            modelBuilder.Entity("Fleet.TransportationManagement.Models.Trip", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Car");

                    b.Property<string>("InputPoints");

                    b.Property<string>("OptimizedPoints");

                    b.Property<int>("ResidualFuel");

                    b.HasKey("Id");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Fleet.TransportationManagement.Models.Point", b =>
                {
                    b.HasOne("Fleet.TransportationManagement.Models.Trip")
                        .WithMany("NoOptPoints")
                        .HasForeignKey("TripId");
                });
#pragma warning restore 612, 618
        }
    }
}
