// <auto-generated />
using System;
using Fleet.TransportationManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fleet.TransportationManagement.Migrations
{
    [DbContext(typeof(TmContext))]
    [Migration("20200402181005_ChangeBrandId")]
    partial class ChangeBrandId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fleet.TransportationManagement.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId");

                    b.Property<int>("Consumption");

                    b.Property<string>("Model");

                    b.Property<int>("Tank");

                    b.HasKey("Id");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("Fleet.TransportationManagement.Models.Trip", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CarId");

                    b.Property<string>("InputPoints");

                    b.Property<string>("OptimizedPoints");

                    b.Property<int>("ResidualFuel");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Fleet.TransportationManagement.Models.Trip", b =>
                {
                    b.HasOne("Fleet.TransportationManagement.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId");
                });
#pragma warning restore 612, 618
        }
    }
}
